### ISSUE TITLE
项目很不错~后续有升级为 TS 的想法不？

### ISSUE THREAD

**Issue by Snailclimb** [kongyijilafumi/react-ant-admin#1]

**Comment by kongyijilafumi** [comment]
会考虑ts版本的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kongyijilafumi/react-ant-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月8日(星期六) 上午10:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[kongyijilafumi/react-ant-admin] 项目很不错~后续有升级为 TS 的想法不？ (#1)

**Comment by kongyijilafumi** [comment]
在项目完善之后会考虑转向**ts**版本

**Comment by Snailclimb** [comment]
> 在项目完善之后会考虑转向**ts**版本

好的！已 star~👍

**Comment by kongyijilafumi** [comment]
> > 在项目完善之后会考虑转向**ts**版本
> 
> 好的！已 star~👍

**Comment by kongyijilafumi** [comment]
> > 在项目完善之后会考虑转向**ts**版本
> 
> 好的！已 star~👍

谢谢
