### ISSUE TITLE
本地控制台提示No routes matched location 

### ISSUE THREAD

**Issue by luckycui-cyber** [kongyijilafumi/react-ant-admin#6]
作者你好，本地运行vite分支代码，登陆成功后，控制台提示No routes matched location "/" 。在任何页面刷新浏览器也会提示No routes matched location "/当前页路径"。

**Comment by kongyijilafumi** [comment]
> 作者你好，本地运行vite分支代码，登陆成功后，控制台提示No routes matched location "/" 。在任何页面刷新浏览器也会提示No routes matched location "/当前页路径"。

已经解决了，请拉最新的代码即可。

**Comment by luckycui-cyber** [comment]
> > 作者你好，本地运行vite分支代码，登陆成功后，控制台提示No routes matched location "/" 。在任何页面刷新浏览器也会提示No routes matched location "/当前页路径"。
> 
> 已经解决了，请拉最新的代码即可。

好的，辛苦作者~
